import type { Metadata } from 'next'
import './globals.css'
import React from 'react'
import AuthProvider from '@/auth/auth-provider'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className='w-full flex flex-col' id='body'>
        <AuthProvider>
          <main className='flex'>
            <div className='w-screen'>{children}</div>
          </main>
        </AuthProvider>
      </body>
    </html>
  )
}
